# Generated by Django 4.1.8 on 2023-04-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actuator',
            old_name='state',
            new_name='value',
        ),
    ]
